# References:
## https://github.com/marketplace/actions/merge-conflict-finder
## https://blog.marcnuri.com/triggering-github-actions-across-different-repositories
## https://github.com/marketplace/actions/merge-branch

name: New Release

on:
  workflow_dispatch:
    inputs:
      distinct_id:
        description: "Distinct ID"
        required: true
      version_number:
        description: "Version number"
        required: true
      release:
        type: choice
        description: Release environemnt
        required: true
        options:
          - beta
          - production

jobs:
  execute-tagging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: beta
      - name: Set environment variables from project settings
        run: |
          exec .github/scripts/run.sh ${{ github.event.inputs.release }} ${{ github.event.inputs.version_number }}

      - name: Merge release -> beta
        run: |
          git checkout beta
          git tag "v-${{ github.event.inputs.build-type }}-release-${{ env.version-number }}"
          git push origin --tags