# References:
## https://github.com/marketplace/actions/merge-conflict-finder
## https://blog.marcnuri.com/triggering-github-actions-across-different-repositories
## https://github.com/marketplace/actions/merge-branch

name: New Release

on:
  workflow_dispatch:
    inputs:
      distinct_id:
        description: "Distinct ID"
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Merge development -> beta
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: development
          target_branch: beta
          github_token: ${{ github.token }}

      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ github.token }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: echo distinct ID ${{ github.event.inputs.distinct_id }}
        run: echo ${{ github.event.inputs.distinct_id }}
