# References:
## https://github.com/marketplace/actions/merge-conflict-finder
## https://blog.marcnuri.com/triggering-github-actions-across-different-repositories
## https://github.com/marketplace/actions/merge-branch

name: New Release

on:
  workflow_dispatch:
    inputs:
      distinct_id:
        description: "Distinct ID"
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@master
      # - name: Merge development -> beta
      #   uses: devmasx/merge-branch@master
      #   with:
      #     type: now
      #     from_branch: development
      #     target_branch: beta
      #     github_token: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          ref: refs/remotes/origin/beta
      - uses: actions/checkout@v3
      - run: |
          git merge --no-commit --no-ff beta
          echo $?
          git merge --abort

      - name: echo distinct ID ${{ github.event.inputs.distinct_id }}
        run: echo ${{ github.event.inputs.distinct_id }}
